import type { Receipt } from "@/types";
import { formatCurrency, formatDate } from "./utils";

export async function generateReceiptPDF(receipt: Receipt): Promise<void> {
  const { jsPDF } = await import("jspdf");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a5" });
  const W = 148;
  const margin = 14;
  let y = 0;

  // Background
  doc.setFillColor(10, 10, 15);
  doc.rect(0, 0, W, 210, "F");

  // Header bar
  doc.setFillColor(230, 57, 70);
  doc.rect(0, 0, W, 28, "F");

  // Logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("RESELLER OS", margin, 12);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("PROOF OF SALE", margin, 19);

  // Receipt number top right
  doc.setFontSize(8);
  doc.text(receipt.receiptNumber, W - margin, 12, { align: "right" });
  doc.text(formatDate(receipt.date), W - margin, 19, { align: "right" });

  y = 36;

  // Seller info block
  doc.setFillColor(22, 22, 31);
  doc.roundedRect(margin, y, W - margin * 2, 24, 2, 2, "F");

  doc.setTextColor(136, 136, 160);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("SELLER", margin + 4, y + 7);

  doc.setTextColor(240, 240, 245);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(receipt.sellerName, margin + 4, y + 14);

  doc.setTextColor(136, 136, 160);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  const sellerContact = [receipt.sellerEmail, receipt.sellerPhone].filter(Boolean).join("  •  ");
  doc.text(sellerContact, margin + 4, y + 20);

  y += 32;

  // Customer block
  doc.setFillColor(22, 22, 31);
  doc.roundedRect(margin, y, W - margin * 2, 18, 2, 2, "F");

  doc.setTextColor(136, 136, 160);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("SOLD TO", margin + 4, y + 7);

  doc.setTextColor(240, 240, 245);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(receipt.customerName, margin + 4, y + 14);

  y += 26;

  // Item
  doc.setTextColor(136, 136, 160);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  doc.text("ITEM", margin, y + 4);
  y += 8;
  doc.setTextColor(240, 240, 245);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  const itemLines = doc.splitTextToSize(receipt.itemName, W - margin * 2);
  doc.text(itemLines, margin, y);
  y += itemLines.length * 6 + 6;

  // Divider
  doc.setDrawColor(30, 30, 42);
  doc.setLineWidth(0.3);
  doc.line(margin, y, W - margin, y);
  y += 8;

  // Line items
  const lineItems = [
    ["Sale Price", formatCurrency(receipt.salePrice)],
    ["Shipping", formatCurrency(receipt.shippingCost)],
    ...(receipt.tax > 0 ? [["Tax", formatCurrency(receipt.tax)]] : []),
  ];

  for (const [label, value] of lineItems) {
    doc.setTextColor(136, 136, 160);
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.text(label, margin, y);
    doc.text(value, W - margin, y, { align: "right" });
    y += 7;
  }

  y += 2;
  // Total line
  doc.setFillColor(230, 57, 70);
  doc.rect(margin, y, W - margin * 2, 0.5, "F");
  y += 6;

  doc.setTextColor(240, 240, 245);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("TOTAL", margin, y);
  doc.text(formatCurrency(receipt.total), W - margin, y, { align: "right" });

  y += 10;
  doc.setTextColor(136, 136, 160);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(`Payment: ${receipt.paymentMethod}`, margin, y);

  if (receipt.notes) {
    y += 8;
    doc.setFontSize(7);
    const noteLines = doc.splitTextToSize(`Note: ${receipt.notes}`, W - margin * 2);
    doc.text(noteLines, margin, y);
    y += noteLines.length * 5;
  }

  y += 10;
  // Verification
  doc.setFillColor(22, 22, 31);
  doc.roundedRect(margin, y, W - margin * 2, 16, 2, 2, "F");
  doc.setTextColor(136, 136, 160);
  doc.setFontSize(7);
  doc.text("VERIFY THIS RECEIPT", margin + 4, y + 6);
  doc.setTextColor(230, 57, 70);
  doc.setFontSize(7);
  doc.text(`Receipt ID: ${receipt.receiptNumber}`, margin + 4, y + 12);

  // Footer
  doc.setFillColor(16, 16, 24);
  doc.rect(0, 198, W, 12, "F");
  doc.setTextColor(85, 85, 106);
  doc.setFontSize(6);
  doc.text("Generated by ResellerOS  •  This is an official proof of sale", W / 2, 205, { align: "center" });

  doc.save(`${receipt.receiptNumber}.pdf`);
}
