import Link from "next/link";
import { TrendingUp, ArrowLeft } from "lucide-react";

function Logo() {
  return (
    <div className="flex items-center gap-2.5">
      <div className="w-8 h-8 rounded-xl bg-accent-red flex items-center justify-center shadow-lg shadow-accent-red/30 shrink-0">
        <TrendingUp size={15} className="text-white" strokeWidth={2.5} />
      </div>
      <div className="leading-none">
        <span className="font-display font-black text-[15px] text-text-primary tracking-tight">RESELLER</span>
        <span className="font-display font-black text-[15px] text-accent-red tracking-tight">OS</span>
      </div>
    </div>
  );
}

const SECTIONS = [
  {
    title: "1. Use of Service",
    body: `ResellerOS is a software tool designed to help resellers track inventory, manage sales, calculate profit, and run their business more effectively. By accessing or using ResellerOS, you agree to use the service only for lawful purposes and in accordance with these Terms. You may not use the service to engage in fraudulent activity, violate any applicable law or regulation, or infringe on the rights of others.`,
  },
  {
    title: "2. Accounts",
    body: `You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately at support@reselleros.com if you suspect any unauthorized use of your account. ResellerOS is not liable for any loss or damage arising from your failure to protect your account credentials. You must provide accurate and complete information when creating an account and keep it up to date.`,
  },
  {
    title: "3. Data & Accuracy",
    body: `ResellerOS provides tools to help you organize and track your reselling business data. We make no guarantee regarding the financial accuracy, completeness, or suitability of any calculations, projections, or reports generated by the app. All figures — including profit estimates, margins, and pricing suggestions — are informational only. You are solely responsible for verifying the accuracy of your own data and for any business decisions you make using information from ResellerOS. We strongly recommend consulting a qualified accountant or financial advisor for official financial reporting.`,
  },
  {
    title: "4. Payments & Subscriptions",
    body: `Paid subscriptions (Pro and Premium plans) are processed securely through Stripe. By subscribing, you authorize recurring charges to your payment method at the applicable plan rate. Subscriptions renew automatically at the end of each billing period unless cancelled. You may cancel your subscription at any time through the Billing page in your account settings. Cancellation takes effect at the end of the current billing period — you will retain access to paid features until then. ResellerOS does not store your payment card information.`,
  },
  {
    title: "5. Refunds",
    body: `All payments are final and non-refundable unless otherwise required by applicable law or expressly stated by ResellerOS in writing. If you believe you have been charged in error, please contact us at support@reselleros.com within 14 days of the charge and we will review your case. We reserve the right to issue refunds at our sole discretion on a case-by-case basis.`,
  },
  {
    title: "6. Limitation of Liability",
    body: `ResellerOS is provided "as is" and "as available" without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the service will be uninterrupted, error-free, or completely secure. To the fullest extent permitted by law, ResellerOS and its operators shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including loss of profits, data, or goodwill — arising from your use of or inability to use the service, or from any decisions made based on data or calculations within the app.`,
  },
  {
    title: "7. Termination",
    body: `We reserve the right to suspend or terminate your account at any time, with or without notice, if we determine that you have violated these Terms, engaged in fraudulent or abusive behavior, or otherwise acted in a manner harmful to other users or to ResellerOS. Upon termination, your right to access the service will immediately cease. You may also delete your account at any time through the Settings page.`,
  },
  {
    title: "8. Changes to These Terms",
    body: `We may update these Terms of Service from time to time to reflect changes to our service, legal requirements, or business practices. We will post the updated Terms on this page with a revised "Last Updated" date. Your continued use of ResellerOS after any changes constitutes your acceptance of the new Terms. If you do not agree with the updated Terms, you should discontinue use of the service.`,
  },
  {
    title: "9. Contact",
    body: `If you have any questions about these Terms of Service, please contact us at support@reselleros.com. We aim to respond to all inquiries within 2 business days.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#08080d] font-body">
      {/* Navbar */}
      <nav className="border-b border-[#1c1c28] bg-[#08080d]/95 backdrop-blur-md">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <Link href="/"><Logo /></Link>
          <Link
            href="/"
            className="flex items-center gap-1.5 text-sm text-text-secondary hover:text-text-primary transition-colors font-medium"
          >
            <ArrowLeft size={14} /> Back to Home
          </Link>
        </div>
      </nav>

      {/* Content */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 py-14">
        {/* Header */}
        <div className="mb-10 pb-8 border-b border-[#1c1c28]">
          <div className="text-[11px] font-display font-black text-accent-red uppercase tracking-widest mb-3">
            Legal
          </div>
          <h1 className="font-display font-black text-4xl text-text-primary tracking-tight mb-3">
            Terms of Service
          </h1>
          <p className="text-text-muted text-sm">
            Last Updated: <span className="text-text-secondary">April 2026</span>
          </p>
          <p className="text-text-secondary text-sm mt-4 leading-relaxed max-w-2xl">
            Please read these Terms of Service carefully before using ResellerOS. By accessing
            or using our service, you agree to be bound by these terms.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-8">
          {SECTIONS.map((section) => (
            <div key={section.title} className="group">
              <h2 className="font-display font-bold text-text-primary text-base mb-3">
                {section.title}
              </h2>
              <p className="text-text-secondary text-sm leading-[1.75] pl-0">
                {section.body}
              </p>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="mt-12 pt-8 border-t border-[#1c1c28]">
          <div className="bg-[#0f0f17] border border-[#1c1c28] rounded-2xl p-5">
            <p className="text-text-muted text-xs leading-relaxed">
              These Terms of Service are effective as of April 2026. For questions or
              concerns, email us at{" "}
              <a
                href="mailto:support@reselleros.com"
                className="text-accent-red hover:underline"
              >
                support@reselleros.com
              </a>
              . You can also review our{" "}
              <Link href="/privacy" className="text-accent-red hover:underline">
                Privacy Policy
              </Link>
              .
            </p>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-[#1c1c28] py-8 px-4 sm:px-6 mt-10">
        <div className="max-w-4xl mx-auto flex flex-col sm:flex-row items-center justify-between gap-4">
          <Logo />
          <div className="flex flex-wrap items-center justify-center gap-5 text-xs text-text-muted">
            <Link href="/"              className="hover:text-text-secondary transition-colors">Home</Link>
            <Link href="/login"         className="hover:text-text-secondary transition-colors">Login</Link>
            <Link href="/signup"        className="hover:text-text-secondary transition-colors">Sign Up</Link>
            <Link href="/privacy"       className="hover:text-text-secondary transition-colors">Privacy Policy</Link>
            <Link href="/receipts/verify" className="hover:text-text-secondary transition-colors">Verify Receipt</Link>
          </div>
          <div className="text-xs text-text-muted">© {new Date().getFullYear()} ResellerOS</div>
        </div>
      </footer>
    </div>
  );
}
